apiVersion: v1
kind: Secret
metadata:
  name: laike-apis-secret
  namespace: laike-prod
type: Opaque
stringData:
  DB_URL: jdbc:mysql://rm-xxxx.mysql.rds.aliyuncs.com:3306/v3_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
  DB_USER: root
  DB_PASSWORD: "replace_me"
  REDIS_CLUSTER_NODES: r-1.redis.rds.aliyuncs.com:6379,r-2.redis.rds.aliyuncs.com:6379,r-3.redis.rds.aliyuncs.com:6379
  REDIS_PASSWORD: "replace_me"
  OSS_ENDPOINT: oss-cn-hangzhou.aliyuncs.com
  OSS_BUCKET: laike-prod
  OSS_ACCESS_KEY: "replace_me"
  OSS_ACCESS_SECRET: "replace_me"
