version: '3.8'
services:
  admins:
    image: laike-apis:1.0
    command: [ "java", "-jar", "/app/admins.jar" ]
    networks:
      - laike-network

  apps:
    image: laike-apis:1.0
    command: [ "java", "-jar", "/app/apps.jar" ]
    networks:
      - laike-network

  plugins:
    image: laike-apis:1.0
    command: [ "java", "-jar", "/app/plugins.jar" ]
    networks:
      - laike-network

  comps: # 网关
    image: laike-apis:1.0
    command: [ "java", "-jar", "/app/comps.jar" ]
    ports:
      - "21868:8080"   # 对外暴露 comps
    networks:
      - laike-network

networks:
  laike-network:
    external: true
