spring:
  jmx:
    enabled: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      file-size-threshold: 1
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6339}
    password: ${REDIS_PWD:laiketui18}
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 100
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
    database: ${REDIS_DB:11}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lkt_db}?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: ${DB_USER:root}
    password: ${DB_PWD:123456}
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin123
        allow: 127.0.0.1

push:
  #是否开启 true开启 false 关闭 test
  status: true
  appid: nJaIsWP1Zt5g5XCapMDgs5
  appkey: xgfKQIWvMo7Q0FqrKVMvr3
  mastersecret: QSqJyNRI596TaL0AkbxIx1
  host: http://sdk.open.api.igexin.com/apiex.htm
  #收到消息是否立即启动应用：1为立即启动，2则广播等待客户端自启动
  transmissiontype: 1

dubbo:
  reference:
    generic: true


#seata:
#  enabled: true
#  application-id: laike-core
#  tx-service-group: lkt_tx_group
#  data-source-proxy-mode: AT
#  client:
#    undo:
#      # undo序列化方式  这个值需要在 seata server 的配置中心中修改，否则不生效
#      logSerialization: jackson
#      # 自定义undo表名
#      logTable: undo_log
#    rm:
#      lock:
#        retryInterval: 10
#        retryTimes: 30
#        # 分支事务与其它全局回滚事务冲突时锁策略 默认true，优先释放本地锁让回滚成功
#        retryPolicyBranchRollbackOnConflict: false
#    tm:
#      # 一阶段全局提交结果上报TC重试次数
#      commit-retry-count: 5
#      # 一阶段全局回滚结果上报TC重试次数
#      rollback-retry-count: 5
#      # 分布式事物超时时间
#      default-global-transaction-timeout: 600000
#      # 降级开关,false 不打开
#      degrade-check: false
#      degrade-check-period: 2000
#      degrade-check-allow-times: 10
#  service:
#    # 全局事务开关
#    enableDegrade: false
#    disableGlobalTransaction: false
#    vgroupMapping:
#      lkt_tx_group: default
#    #      system-user-fescar-service-group: default
#    default:
#      grouplist: 127.0.0.1:8091
#  # 是否自动开启数据源代理
#  #enable-auto-data-source-proxy: false
#  # 数据源代理模式，使用AT模式
#  # data-source-proxy-mode: AT
#  # 配置中心，需要和 seata server 保持一致
#  config:
#    type: zk
#    zk:
#      server-addr: 127.0.0.1:2181
#      connect-timeout: 2000
#      session-timeout: 6000
#  # 注册中心，需要和 seata server 保持一致
#  registry:
#    type: zk
#    zk:
#      server-addr: 127.0.0.1:2181
#      connect-timeout: 2000
#      session-timeout: 6000
