apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laike-apis-logs-pvc
  namespace: laike-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laike-apis-upload-pvc
  namespace: laike-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
