apiVersion: v1
kind: ConfigMap
metadata:
  name: laike-apis-bootstrap
  namespace: laike-prod
data:
  bootstrap.yml: |
    server:
      port: 21898
      servlet:
        context-path: /apis
        encoding:
          force: true
          enabled: true
          charset: UTF-8

    spring:
      application:
        name: laike-apis
      cloud:
        nacos:
          config:
            enabled: false
          discovery:
            enabled: false
      redis:
        host: redis-master.redis.svc.cluster.local
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 5
        timeout: 30000
      mail:
        host: smtp.qq.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
      shardingsphere:
        database-name: mysql
        mode:
          type: Memory
          repository:
            type: Memory
          overwrite: true
        datasource:
          names: lkt-ds-master-0
          lkt-ds-master-0:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://mysql-master.mysql.svc.cluster.local:3306/v3_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
            username: ${DB_USER}
            password: ${DB_PASSWORD}

    node:
      ip: 127.0.0.1
      allow-local-host: true
      wx-certp12-path: /opt/laike/apis/certs

    uploadFile:
      path: /opt/laike/apis/upload/

    xxl:
      job:
        accessToken: ""
        admin:
          addresses: http://laike-apis.laike-prod.svc/apis
        executor:
          appname: laike-task
          ip:
          port: 2026
          logpath: /opt/laike/apis/xxl-logs
          logretentiondays: 30

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
