apiVersion: v1
kind: Secret
metadata:
  name: laike-apis-secret
  namespace: laike-prod
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: "replace_me"
  REDIS_PASSWORD: "replace_me"
  MAIL_USERNAME: "replace_me"
  MAIL_PASSWORD: "replace_me"
